zentnerlab/TSRexploreR

R/bam_processing.R
man/import_bams.Rd

Sample sheet was previously not saved to TSRexploreR object. This PR ensures the sample sheet is saved.
Addresses #14

save sample sheet to object when importing bams

---

R/bam_processing.R

Replaced second @ with $ at the indicated location for proper slot access.

fixing apparent typo in addition of sample sheet to TSRexploreR

---

R/TSRexplore.R
R/association.R
R/data_import.R

Returns an error instead of a logical when testing, which breaks input checks.

Changing is.readable to is.character

---

R/tss_shifting.R
man/tss_shift-function.Rd

Consensus ranges of width one are removed prior to analysis, since there can not be a positional shift in this case.
I've also added an argument to optionally filter TSSs by a threshold value.

Improvements to TSS shifting

---

R/tss_shifting.R
src/shiftscore.cpp

This should fix Gabe's difficulty (runs correctly locally). I would note that when I run, I get the following:
```
Joining, by = c("fhash", "sample_indicator")
Warning messages:
1: In .local(x, row.names, optional, ...) : Arguments in '...' ignored
2: In ShiftScores(overlap, baseline_level = sample_1["TSS"], nresamp = n_resamples,  :
Some sequences have fewer than nthresh scores for at least one sample. 
These are ignored and returned as NA.
```
The second warning is to be expected. I'm not sure of the origin of the first. It doesn't have to do with the calculation but likely some tibble conversion or join somewhere else. It would probably be good to make it go away.
Let me know if the scores themselves look odd. The previous issue is that some histograms had lots/large values in them so …

fixes due to numeric overflow for long shift score calculations

---

R/diff_exp_plots.R
man/export_for_enrichment-function.Rd

Unchanged genes are no longer included by default when exporting DEGs for enrichment analysis.
addresses #61

remove unchanged genes when exporting DEGs for enrichment

---

R/tss_shifting.R
man/tss_shift-function.Rd

Renamed the argument 'min_distance' to 'max_distance' in the tss_shifting function. This makes more sense because TSRs below this threshold are merged.
addresses #48

rename min_distance to max_distance for tss_shifting

---

DESCRIPTION
INSTALL.md
R/TSRexplore.R
tests/testthat/test-TSS_processing.R
tests/testthat/test-genome.R

Added unit tests for:
- TSS annotation based on gene or transcript.
- Importing genome assembly from FASTA or BSgenome.
- Importing genome annotation from GTF or TxDb.
Added BSgenome.Scerevisiae.UCSC.sacCer3 and TxDb.Scerevisiae.UCSC.sacCer3.sgdGene to suggests for unit testing.
Fixed a bug where when importing from BSgenome.

TSS annotation and genome related unit tests. BSgenome import bug fix.

---

R/tss_clustering.R
man/dot-aggr_scores.Rd
man/tss_clustering-function.Rd

Made a few changes to TSS clustering.
- Sped up clustering and made it more memory efficient by switching to data.table `foverlaps`.
- Added an argument to specify the maximum TSR width to return.
- Fixed a bug where the number of unique TSSs per TSR was incorrect.

changes to tss_clustering

---

R/thresholding.R
man/apply_threshold.Rd
vignettes/STANDARD_ANALYSIS.Rmd

Added argument `n_samples` to `apply_threshold` to allow specification of number of samples that must meet threshold to keep TSS in all samples.
Also partially addresses #67

modified behavior of apply_threshold

---

tests/testthat/test-bam_processing.R

Unit tests:
- BAM import into GRanges.
- Ensuring GRanges are returned after G correction.
- Ensuring GRanges are returned after TSS aggregation.

adding tests for BAM import and processing

---

R/diff_exp_plots.R
man/plot_num_de-function.Rd

Previously unchanged genes were included in the plot that shows the number of DE features. This PR adds the argument `keep_unchaged` and sets the default value to `FALSE`, so that unchanged genes are no longer included by default.
Addresses #77

Change default behavior of number of DE features plot

---

R/motif.R
tests/testthat/test-sequence_related.R

Wrote basic units tests for:
- ensuring `tss_sequences` returns a proper DataFrame.
- checking that a plot is returned with `plot_sequence_logo` and `plot_sequence_colormap`.
- checking that `dinucleotide_frequencies` returns a proper DataFrame.
- also making sure `plot_dinucleotide_frequencies` returns a plot.
Fixes #82 which was caused by an incorrect variable name for setting factor levels when samples are specified

unit tests for sequence related functions, and big fix for tss_sequences

---

R/tsr_metrics.R
man/iq_range-function.Rd
man/tsr_metrics-function.Rd

Added arguments `iqr_lower` and `iqr_upper` to `tsr_metrics` that allow specification of the IQR bounds. Addresses #74.

allow specification of IQR upper and lower bounds for tsr_metrics

---

R/diff_exp_plots.R
man/export_for_enrichment-function.Rd

Added argument `anno_categories` to `export_for_enrichment` that can take a vector of annotation categories to retain.
fixes #84

Adding annotation category filter to export_for_enrichment

---

R/tss_clustering.R
man/tss_clustering-function.Rd

Added `n_samples` argument to `tss_clustering`. If set TSSs will be retained for clustering if at least `n_samples` have a TSS at a position that is greater than or equal to `threshold`.
addresses #100

added n_samples option to tss_clustering

---

R/genomic_distribution.R
tests/testthat/test-TSS_processing.R
tests/testthat/test-bam_processing.R
tests/testthat/test-differential_features.R
tests/testthat/test-genome.R
tests/testthat/test-heatmap.R
tests/testthat/test-ranges.R
tests/testthat/test-sequence_related.R

Added unit tests for TSS and TSR heatmaps generated from `plot_heatmaps`.
Fixed a bug in `plot_genomic_distribution` that caused an error when sample names were specified.

plot_heatmap unit tests; fixing sample order bug in plot_genomic_distribution

---

R/correlation.R
R/diff_exp_plots.R
R/dinucleotide.R
R/gene_plots.R
R/genomic_distribution.R
R/merge.R
R/motif.R
R/params.R
R/shifting_plots.R
R/softclip_analysis.R
R/thresholding.R
man/common_params.Rd
man/merge_samples-function.Rd
man/plot_correlation-function.Rd
man/plot_detected_features.Rd
man/plot_dinucleotide_frequencies.Rd
man/plot_genomic_distribution.Rd
man/plot_num_de-function.Rd
man/plot_shift_count.Rd
man/plot_threshold_exploration-function.Rd
man/softclip_composition.Rd
tests/testthat/test-heatmap.R

Added the ability to return a table instead of a plot for many plotting functions by setting `return_table=TRUE`.
Functions changed:
- `plot_threshold_exploration`
- `plot_correlation`
- `plot_dinucleotide_frequencies`
- `plot_detected_features`
- `plot_genomic_distribution`
- `plot_shift_count`
- `softclip_composition`
- `plot_num_de`

Option to return a table for many plotting functions.

---

R/gene_plots.R
R/genomic_distribution.R
R/motif.R

Sample orders should now not be reversed for `plot_genomic_distribution` and `plot_sequence_logo`. I also fixed a typo that resulted in sample ordering not working with `plot_detected_features`.
fixes #115

Fixed sample ordering in a few plots

---

R/heatmaps.R
man/plot_heatmap-function.Rd

There was still an input check for `data_conditions` in `plot_heatmap`, which was causing an error. This has been removed.

fixed old refrence to data_conditions in plot_heatmap

---

R/tss_clustering.R
man/dot-aggr_scores.Rd
man/tss_clustering-function.Rd

Added argument `singlet_threshold` to `tss_clustering` that allows the specification of a score threshold for singlets.

added threshold for singlets in tss_clustering

---

vignettes/DATA_CONDITIONING.Rmd

Originally forgot to change the vignette name in the data conditioning vignette.

fixed typo in data conditioning vignette header

---

R/heatmaps.R

Fixed bug with `plot_heatmap` when a data.frame was supplied to `split_by`. This was caused by `is.list` evaluating to TRUE for data.frames.
fixes #151

fixing plot_heatmap bug

---

R/tss_shifting.R

Specified the namespace for `pivot_wider`.
Fixed an incorrect variable name.

fixing bugs in tss_shift

---

inst/singularity/singularity-recipe

Loading the ChIPseeker library resulted in an error because of DO.db within the singularity container. I updated the recipe to resolve this issue.

updating singularity recipe to fix ChIPseeker error
